{% set name = "rr" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: https://test.pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fa72ab05f0bdf67dc68c4e8896833e8b3a12d0fcd73ef0027a46f521d327a74d

build:
  noarch: python
  number: 0
  entry_points:
    - rr-paper = rr.paper:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - python
    - pip
  run:
    - setuptools
    - python >=3.7
    - numpy ==1.19.1
    - scipy ==1.5.2

test:
  source_files:
    - doc/
  requires:
    - nose
    - coverage
    - sphinx
    - sphinx_rtd_theme
  imports:
    - rr
  commands:
    - rr-paper
    - sphinx-build -aEb doctest doc sphinx
    - nosetests -sv --with-coverage --cover-package=rr rr


about:
  home: https://test.pypi.org/project/rr
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: Basic example of a Reproducible Research Project in Python
  doc_url: https://idiap.github.io/mai-m05-ex6/index.html
  dev_url: https://github.com/idiap/mai-m05-ex6

extra:
  recipe-maintainers:
    - anjos
