{% set name = "rr" %}
{% set version = "2.0.1" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: https://test.pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fc99551a078bff655930f4d8e54674d9b8bd01f54571974423a16ec377f00392

build:
  noarch: python
  number: 0
  entry_points:
    - rr-paper = rr.paper:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - python
    - pip
  run:
    - setuptools
    - python >=3.8
    - numpy ==1.20.3
    - scipy ==1.7.1

test:
  requires:
    - pytest
  imports:
    - rr
  commands:
    - rr-paper --help
    - pytest -sv --pyargs rr


about:
  home: https://test.pypi.org/project/rr
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: Basic example of a Reproducible Research Project in Python
  doc_url: https://idiap.github.io/mai-m05-ex6/index.html
  dev_url: https://github.com/idiap/mai-m05-ex6

extra:
  recipe-maintainers:
    - anjos
