{% set name = "rr" %}
{% set version = "2.0.0" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: https://test.pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b52e318a1a0f25847ee00ba2c4ab644e709f9fa2e59160b56608870dda22eb05

build:
  noarch: python
  number: 0
  entry_points:
    - rr-paper = rr.paper:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - python
    - pip
  run:
    - setuptools
    - python >=3.8
    - numpy ==1.20.3
    - scipy ==1.7.1

test:
  requires:
    - pytest
  imports:
    - rr
  commands:
    - rr-paper --help
    - pytest -sv --cov=rr rr


about:
  home: https://test.pypi.org/project/rr
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: Basic example of a Reproducible Research Project in Python
  doc_url: https://idiap.github.io/mai-m05-ex6/index.html
  dev_url: https://github.com/idiap/mai-m05-ex6

extra:
  recipe-maintainers:
    - anjos
