variables:
  PYTHONUNBUFFERED: "1"
  CONDA_ROOT: "${CI_PROJECT_DIR}/miniconda"
  BOOTSTRAP: "https://gitlab.idiap.ch/bob/bob.devtools/raw/master/bob/devtools/bootstrap.py"

stages:
  - build

build:
  stage: build
  tags:
    - docker
  image: continuumio/conda-concourse-ci
  before_script:
    # download miniconda installer and installs miniconda
    - curl --silent "${BOOTSTRAP}" --output "bootstrap.py"
    - python3 bootstrap.py -vv channel base
    - source ${CONDA_ROOT}/etc/profile.d/conda.sh
    - conda activate base
  script:
    # build and test
    - conda build --python=3.7 recipe
    - conda convert ${CONDA_ROOT}/conda-bld/linux-64/rr-*.tar.bz2 --platform osx-64 --output ${CONDA_ROOT}/conda-bld
    - conda convert ${CONDA_ROOT}/conda-bld/linux-64/rr-*.tar.bz2 --platform win-64 --output ${CONDA_ROOT}/conda-bld
  after_script:
    # deployment
    - conda install anaconda-client
    - anaconda -t ${ANACONDA_TOKEN} upload -u ${ANACONDA_USER} ${CONDA_ROOT}/conda-bld/*-64/rr*.tar.bz2 --force
  cache:
    # this avoids re-downloading the installer at every build
    paths:
      - miniconda.sh
